import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

const translations = {
  en: {
    // App
    appName: '语闻',
    appSubtitle: 'A way to beat WeChat',

    // Auth
    login: 'Login',
    register: 'Register',
    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    loginBtn: 'Login',
    registerBtn: 'Register',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    registerHere: 'Register here',
    loginHere: 'Login here',

    // Chat
    myCode: 'My Code',
    addFriend: 'Add Friend',
    newGroup: 'New Group',
    joinGroup: 'Join Group',
    friendRequests: 'Friend Requests',
    friends: 'Friends',
    groups: 'Groups',
    online: 'Online',
    offline: 'Offline',
    noFriends: 'No friends yet',
    noGroups: 'No groups yet',
    selectChat: 'Select a chat to start messaging',
    encrypted: 'Your messages are end-to-end encrypted',
    typeMessage: 'Type a message...',
    sent: 'Sent',
    delivered: 'Delivered',
    read: 'Read',
    edited: 'edited',
    accept: 'Accept',
    reject: 'Reject',

    // Message actions
    edit: 'Edit',
    delete: 'Delete',
    deleteMessage: 'Delete Message',
    deleteForMe: 'Delete for me',
    deleteForBoth: 'Delete for both',
    cancel: 'Cancel',
    save: 'Save',
    editMessage: 'Edit Message',
    confirmDelete: 'Are you sure you want to delete this message?',
    alsoDeleteForOther: 'Also delete for the other person',

    // Modals
    searchByCode: 'Search by friend code',
    friendCode: 'Friend Code',
    search: 'Search',
    userNotFound: 'User not found',
    sendRequest: 'Send Request',
    requestSent: 'Request sent!',
    groupName: 'Group Name',
    create: 'Create',
    groupCode: 'Group Code',
    join: 'Join',
    leave: 'Leave Group',
    members: 'members',

    // Settings
    settings: 'Settings',
    language: 'Language',
    english: 'English',
    chinese: '中文',
    logout: 'Logout',
    darkMode: 'Dark Mode',
    security: 'Security',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password (leave empty to keep)',
    confirmNewPassword: 'Confirm New Password',
    fillAllFields: 'Please fill all fields',
    passwordTooShort: 'Password must be at least 6 characters',
    passwordMismatch: 'Passwords do not match',
    passwordChanged: 'Password changed successfully',
    passwordChangeFailed: 'Failed to change password',
    saving: 'Saving...',

    // Avatar
    avatar: 'Avatar',
    uploadAvatar: 'Upload Image',
    removeAvatar: 'Remove',
    backgroundColor: 'Background Color',
    avatarUpdated: 'Avatar updated!',
    avatarRemoved: 'Avatar removed',
    avatarUploadFailed: 'Failed to upload avatar',
    avatarRemoveFailed: 'Failed to remove avatar',
    colorChangeFailed: 'Failed to change color',
    invalidImageType: 'Please select an image file',
    imageTooLarge: 'Image too large (max 2MB)',

    // Admin
    adminPanel: 'Admin Panel',
    backToChat: 'Back to Chat',
    totalUsers: 'Total Users',
    messages: 'Messages',
    friendships: 'Friendships',
    users: 'Users',
    actions: 'Actions',
    created: 'Created',
    admin: 'Admin',
    user: 'User',
    private: 'Private',
    group: 'Group',
    status: 'Status',
    from: 'From',
    to: 'To',
    type: 'Type',
    previous: 'Previous',
    next: 'Next',
    editUser: 'Edit User',
    newPassword: 'New Password (leave empty to keep)',
    confirmDeleteUser: 'Delete user "{username}"? This cannot be undone.',
    confirmDeleteGroup: 'Delete group "{name}"? This cannot be undone.',
    confirmDeleteMessage: 'Delete this message? This cannot be undone.',

    // File
    fileTooLarge: 'File too large. Maximum size is 10MB.',
    uploadFailed: 'Failed to send file',

    // Unlock
    unlockTitle: 'Unlock Session',
    unlockDescription: 'Enter your password to decrypt your private key',
    unlock: 'Unlock',
    unlocking: 'Unlocking...',
    invalidPassword: 'Invalid password',

    // Security
    securityVerification: 'Security Verification',
    emojiDescription: 'If you and your friend see the same emojis, your chat is secure',
    verifyStep1: 'Contact your friend in person or by phone',
    verifyStep2: 'Compare the emojis shown on both screens',
    verifyStep3: 'If they match, no one is eavesdropping',
    groupSecurityInfo: 'Group uses symmetric encryption. The key is generated by the creator and securely shared with members.',
    howItWorks: 'How does encryption protect you?',
    e2eTitle: 'End-to-End Encryption',
    e2eDescription: 'Messages are encrypted on your device. Only the recipient can decrypt them. The server only sees gibberish.',
    keyTitle: 'Your Private Key',
    keyDescription: 'Your private key is encrypted with your password. Even if the server is hacked, they cannot decrypt without your password.',
    noAccessTitle: 'We Cannot Read',
    noAccessDescription: 'We (server admins) can never read your messages. This is mathematically guaranteed.',
    yourFingerprint: 'Your Public Key Fingerprint',
    fingerprintNote: 'You can share this with others to verify your identity',
    gotIt: 'Got it',

    // Updates
    updates: 'Updates',
    currentVersion: 'Current Version',
    branch: 'Branch',
    commit: 'Commit',
    checkUpdates: 'Check Updates',
    applyUpdate: 'Apply Update',
    selectBranch: 'Select Branch',
    noUpdates: 'Already up to date',
    updatesAvailable: 'Updates available',
    filesChanged: 'Files changed',
    newCommits: 'New commits',
    updating: 'Updating...',
    updateSuccess: 'Update successful!',
    updateFailed: 'Update failed',
    localChanges: 'Local changes detected',
    stashChanges: 'Stash local changes',
    databaseWarning: 'Warning: Database files may be affected',
    restartRequired: 'Restart Required',
    autoBuild: 'Auto Build',
    autoRestart: 'Auto Restart',
    stageFetching: 'Fetching code...',
    stageMerging: 'Merging updates...',
    stageInstalling: 'Installing dependencies...',
    stageBuilding: 'Building client...',
    stageRestarting: 'Restarting server...',
    buildFailed: 'Build failed',
    serverRestarting: 'Server is restarting, please wait...',
    clientChanged: 'Client files changed',
    serverChanged: 'Server files changed',
    reconnecting: 'Reconnecting...'
  },
  zh: {
    // App
    appName: '语闻',
    appSubtitle: '是一个干翻微信的方式',

    // Auth
    login: '登录',
    register: '注册',
    username: '用户名',
    password: '密码',
    confirmPassword: '确认密码',
    loginBtn: '登录',
    registerBtn: '注册',
    noAccount: '没有账号？',
    hasAccount: '已有账号？',
    registerHere: '点此注册',
    loginHere: '点此登录',

    // Chat
    myCode: '我的代码',
    addFriend: '添加好友',
    newGroup: '新建群组',
    joinGroup: '加入群组',
    friendRequests: '好友请求',
    friends: '好友',
    groups: '群组',
    online: '在线',
    offline: '离线',
    noFriends: '还没有好友',
    noGroups: '还没有群组',
    selectChat: '选择一个聊天开始发消息',
    encrypted: '您的消息已端对端加密',
    typeMessage: '输入消息...',
    sent: '已发送',
    delivered: '已送达',
    read: '已读',
    edited: '已编辑',
    accept: '接受',
    reject: '拒绝',

    // Message actions
    edit: '编辑',
    delete: '删除',
    deleteMessage: '删除消息',
    deleteForMe: '仅删除我的',
    deleteForBoth: '双方都删除',
    cancel: '取消',
    save: '保存',
    editMessage: '编辑消息',
    confirmDelete: '确定要删除这条消息吗？',
    alsoDeleteForOther: '同时删除对方的消息',

    // Modals
    searchByCode: '通过好友代码搜索',
    friendCode: '好友代码',
    search: '搜索',
    userNotFound: '未找到用户',
    sendRequest: '发送请求',
    requestSent: '请求已发送！',
    groupName: '群组名称',
    create: '创建',
    groupCode: '群组代码',
    join: '加入',
    leave: '退出群组',
    members: '成员',

    // Settings
    settings: '设置',
    language: '语言',
    english: 'English',
    chinese: '中文',
    logout: '退出登录',
    darkMode: '深色模式',
    security: '安全',
    changePassword: '修改密码',
    currentPassword: '当前密码',
    newPassword: '新密码（留空保持不变）',
    confirmNewPassword: '确认新密码',
    fillAllFields: '请填写所有字段',
    passwordTooShort: '密码至少6个字符',
    passwordMismatch: '两次密码不一致',
    passwordChanged: '密码修改成功',
    passwordChangeFailed: '修改密码失败',
    saving: '保存中...',

    // Avatar
    avatar: '头像',
    uploadAvatar: '上传图片',
    removeAvatar: '移除',
    backgroundColor: '背景颜色',
    avatarUpdated: '头像已更新！',
    avatarRemoved: '头像已移除',
    avatarUploadFailed: '上传头像失败',
    avatarRemoveFailed: '移除头像失败',
    colorChangeFailed: '更换颜色失败',
    invalidImageType: '请选择图片文件',
    imageTooLarge: '图片太大（最大2MB）',

    // Admin
    adminPanel: '管理员面板',
    backToChat: '返回聊天',
    totalUsers: '用户总数',
    messages: '消息',
    friendships: '好友关系',
    users: '用户',
    actions: '操作',
    created: '创建时间',
    admin: '管理员',
    user: '用户',
    private: '私聊',
    group: '群组',
    status: '状态',
    from: '发送者',
    to: '接收者',
    type: '类型',
    previous: '上一页',
    next: '下一页',
    editUser: '编辑用户',
    newPassword: '新密码（留空保持不变）',
    confirmDeleteUser: '删除用户"{username}"？此操作无法撤销。',
    confirmDeleteGroup: '删除群组"{name}"？此操作无法撤销。',
    confirmDeleteMessage: '删除这条消息？此操作无法撤销。',

    // File
    fileTooLarge: '文件太大，最大支持10MB。',
    uploadFailed: '发送文件失败',

    // Unlock
    unlockTitle: '解锁会话',
    unlockDescription: '输入密码解锁您的私钥',
    unlock: '解锁',
    unlocking: '解锁中...',
    invalidPassword: '密码错误',

    // Security
    securityVerification: '安全验证',
    emojiDescription: '如果你和对方看到的表情一样，说明聊天是安全的',
    verifyStep1: '面对面或通过电话联系对方',
    verifyStep2: '比较双方屏幕上显示的表情',
    verifyStep3: '如果完全一致，说明没有人在窃听',
    groupSecurityInfo: '群组使用对称加密，密钥由创建者生成并安全分发给成员。',
    howItWorks: '加密是如何保护你的？',
    e2eTitle: '端对端加密',
    e2eDescription: '消息在你的设备上加密，只有接收者能解密。服务器只能看到乱码。',
    keyTitle: '你的私钥',
    keyDescription: '私钥用你的密码加密后存储，即使服务器被黑，没有你的密码也无法解密。',
    noAccessTitle: '我们无法查看',
    noAccessDescription: '我们（服务器管理员）永远无法阅读你的消息内容。这是数学保证的。',
    yourFingerprint: '你的公钥指纹',
    fingerprintNote: '可以分享给别人用于验证身份',
    gotIt: '知道了',

    // Updates
    updates: '系统更新',
    currentVersion: '当前版本',
    branch: '分支',
    commit: '提交',
    checkUpdates: '检查更新',
    applyUpdate: '应用更新',
    selectBranch: '选择分支',
    noUpdates: '已是最新版本',
    updatesAvailable: '有可用更新',
    filesChanged: '文件变更',
    newCommits: '新提交',
    updating: '更新中...',
    updateSuccess: '更新成功！',
    updateFailed: '更新失败',
    localChanges: '检测到本地修改',
    stashChanges: '暂存本地修改',
    databaseWarning: '警告：数据库文件可能受影响',
    restartRequired: '需要重启',
    autoBuild: '自动构建',
    autoRestart: '自动重启',
    stageFetching: '正在获取代码...',
    stageMerging: '正在合并更新...',
    stageInstalling: '正在安装依赖...',
    stageBuilding: '正在构建前端...',
    stageRestarting: '正在重启服务器...',
    buildFailed: '构建失败',
    serverRestarting: '服务器正在重启，请稍候...',
    clientChanged: '前端文件已更新',
    serverChanged: '后端文件已更新',
    reconnecting: '正在重新连接...'
  }
}

export const useLanguageStore = defineStore('language', () => {
  const currentLang = ref(localStorage.getItem('lang') || 'en')

  const t = computed(() => {
    return (key, params = {}) => {
      let text = translations[currentLang.value]?.[key] || translations.en[key] || key
      // Replace parameters like {username}
      Object.keys(params).forEach(param => {
        text = text.replace(`{${param}}`, params[param])
      })
      return text
    }
  })

  function setLanguage(lang) {
    currentLang.value = lang
    localStorage.setItem('lang', lang)
  }

  return {
    currentLang,
    t,
    setLanguage
  }
})
